<?php

namespace mod_amcquiz\entity;

class parameters
{
    public $id;
    public $amcquiz_id;
    public $displaypoints;
    public $versions;
    public $separatesheet;
    public $shuffleq;
    public $shufflea;
    public $randomseed; // should be generated by AMC API ?
    public $qcolumns;
    public $acolumns;
    public $studentnumberinstructions;// (instructions for student number)
    public $studentnameinstructions; // (instructions for student name)
    public $scoringset; // (index de l'élément sélectionné. éléments définis dans les settings du plugin)
    public $markmulti;// (shows a symbol if mutliple valid answers)
    public $showscalemode; // (affichage du mode de barême)
    public $minscore;
    public $grademax;
    public $gradegranularity;
    public $graderounding;
    public $instructionsprefix;
    public $instructionsprefixformat;
    public $customlayout;
}
